[package]
name = "zex"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "2.33.3"
features = ["yaml"]

[dependencies.tui]
version = "0.16.0"

[dependencies.termion]
version = "1.5.6"
